### ISSUE TITLE
Incorrect Enum creation causes crash with python 3.8

### ISSUE THREAD

**Issue by cmd410** [kiriharu/fish_text_ru#1]
This code doesn't work:
```python
from enum import Enum


class StrEnum(Enum, str):
    pass


class TextType(StrEnum):
    Sentence = "sentence"
    Paragraph = "paragraph"
    Title = "title"
```

It crashes python with error:
```TypeError: new enumerations should be created as `EnumName([mixin_type, ...] [data_type,] enum_type)```

Typed enums must inherit base type first and Enum - last:
This will work fine:
```python
from enum import Enum


class StrEnum(str, Enum):
    pass


class TextType(StrEnum):
    Sentence = "sentence"
    Paragraph = "paragraph"
    Title = "title"
```

Altough, I propose to avoid StrEnum class as it serves not real purpose here, you just write `(StrEnum)` instead of `(str, Enum)`

**Comment by kiriharu** [comment]
Thank you for issue!
