### ISSUE TITLE
Классы не нужны

### ISSUE THREAD

**Issue by deknowny** [kiriharu/fish_text_ru#3]
Каждый из классов, с помощью которых делается запрос, лишь имеет один единственный метод, которым можно пользоваться (`get`).

Предлагаю из классов сделать обычные функции

**Comment by kiriharu** [comment]
Это сделано (по большей части) лишь в угоду абстракциям. 
Возможно, автор библиотеки добавит какие-то новые методы или на основе существующих классов я сделаю обертку (хотел сделать для генерации и тестирования Markdown, но пока руки не доходят). Пускай стоит так, не думаю что это слишком критично :)
